// Generated by tools/gen-presets.js from shader/blackhole.glsl - do not edit.
#pragma once
#include "renderer.h"

static const float kLookDefaults[LOOK_COUNT] = {
  5500.f, 1.5f, 0.35f, 1.8f, 8.f, 0.9f, 0.6f, 2.5f, 2.2f, 1.6f, 7.f, 5.f, 1.4f, 0.f, 0.02f, 13.f, 0.33f, 0.2f, 0.01f, 0.5f, 1.f, 1.f, 0.04f, 1.1f, 0.96f, 0.04f,
};

struct Preset { const wchar_t* name; float look[14]; };  // LOOK_FIELDS order == Look enum 0..13
static const Preset kPresets[] = {
  { L"inferno", { 5500.f, 1.5f, 0.35f, 1.8f, 8.f, 0.9f, 0.6f, 2.5f, 2.2f, 1.6f, 7.f, 5.f, 1.4f, 0.f } },
  { L"gargantua", { 4500.f, 1.52f, 0.1f, 2.2f, 7.f, 0.85f, 0.35f, 2.f, 1.4f, 0.5f, 7.f, 5.f, 1.2f, 0.f } },
  { L"m87* donut", { 3800.f, 0.55f, -0.3f, 2.2f, 6.f, 0.45f, 0.9f, 3.5f, 1.6f, 0.4f, 3.f, 2.5f, 1.1f, 0.f } },
  { L"face-on ember", { 6500.f, 0.3f, 0.f, 3.f, 10.f, 0.5f, 0.8f, 2.5f, 1.f, 1.1f, 7.f, 5.f, 1.f, 0.f } },
  { L"quasar", { 15000.f, 1.3f, 0.35f, 3.f, 14.f, 0.35f, 1.f, 4.f, 1.2f, 1.3f, 8.f, 5.f, 0.8f, 0.f } },
  { L"blazar", { 18000.f, 1.05f, 0.55f, 3.f, 16.f, 0.3f, 1.f, 5.f, 1.f, 1.5f, 9.f, 6.f, 0.75f, 0.f } },
  { L"pure lens", { 5500.f, 1.5f, 0.35f, 1.8f, 8.f, 0.f, 1.f, 2.5f, 0.f, 1.6f, 7.f, 5.f, 1.f, 0.6f } },
};
static const int kPresetCount = 7;
