'use strict';
// Emits native/src/presets.gen.h from the vendored GLSL via src/shader-patch.js, so the
// upstream shader stays the single source of truth for defaults and look presets.
//     node tools/gen-presets.js
const path = require('path');
const fs = require('fs');
const { build, presets, PROMOTE, LOOK_FIELDS } = require(path.join(__dirname, '..', 'src', 'shader-patch.js'));

const defaults = build().defaults;
const looks = presets();
const f = v => Number.isInteger(v) ? `${v}.f` : `${v}f`;
let out = `// Generated by tools/gen-presets.js from shader/blackhole.glsl - do not edit.
#pragma once
#include "renderer.h"

static const float kLookDefaults[LOOK_COUNT] = {
  ${PROMOTE.map(n => f(defaults[n])).join(', ')},
};

struct Preset { const wchar_t* name; float look[${LOOK_FIELDS.length}]; };  // LOOK_FIELDS order == Look enum 0..${LOOK_FIELDS.length - 1}
static const Preset kPresets[] = {
${looks.map(p => `  { L"${p.name}", { ${LOOK_FIELDS.map(n => f(p.look[n])).join(', ')} } },`).join('\n')}
};
static const int kPresetCount = ${looks.length};
`;
fs.writeFileSync(path.join(__dirname, '..', 'native', 'src', 'presets.gen.h'), out);
console.log(`presets.gen.h: ${PROMOTE.length} defaults, ${looks.length} presets: ${looks.map(p => p.name).join(', ')}`);
